In [16]:
import numpy as np
import pandas as pd
qno=np.array([(i+1) for i in range(15)])
prize=["₹1,000","₹2,000","₹3,000","₹5,000","₹10,000","₹20,000","₹40,000","₹80,000","₹1,60,000","₹3,20,000","₹6,40,000","₹12,50,000","₹25,00,000","₹50,00,000","₹1,00,00,000 (1 Crore)"] 
level={
    "Q.No":qno,
    "Prize Money":prize
}
df
# df=pd.DataFrame(level)
# df.to_csv('Question Levels.csv', index=False)
# print(df.to_string(index=False))

    Q.No             Prize Money
0      1                  ₹1,000
1      2                  ₹2,000
2      3                  ₹3,000
3      4                  ₹5,000
4      5                 ₹10,000
5      6                 ₹20,000
6      7                 ₹40,000
7      8                 ₹80,000
8      9               ₹1,60,000
9     10               ₹3,20,000
10    11               ₹6,40,000
11    12              ₹12,50,000
12    13              ₹25,00,000
13    14              ₹50,00,000
14    15  ₹1,00,00,000 (1 Crore)

In [17]:
df=pd.DataFrame(level)
df.to_csv('Question Levels.csv', index=False)
print(df.to_string(index=False))

 Q.No            Prize Money
    1                 ₹1,000
    2                 ₹2,000
    3                 ₹3,000
    4                 ₹5,000
    5                ₹10,000
    6                ₹20,000
    7                ₹40,000
    8                ₹80,000
    9              ₹1,60,000
   10              ₹3,20,000
   11              ₹6,40,000
   12             ₹12,50,000
   13             ₹25,00,000
   14             ₹50,00,000
   15 ₹1,00,00,000 (1 Crore)

In [19]:
df["Milestone?"]=None
df.loc[df["Q.No"]==5,"Milestone?"]="✅Level 1 - Complete"
df.loc[df["Q.No"]==10,"Milestone?"]="✅Level 2 - Complete"
df.loc[df["Q.No"]==15,"Milestone?"]="✅Final Prize😎"
df = df.fillna('Keep going👍')
df.to_csv('Question Levels.csv', index=False)
df

    Q.No             Prize Money           Milestone?
0      1                  ₹1,000          Keep going👍
1      2                  ₹2,000          Keep going👍
2      3                  ₹3,000          Keep going👍
3      4                  ₹5,000          Keep going👍
4      5                 ₹10,000  ✅Level 1 - Complete
5      6                 ₹20,000          Keep going👍
6      7                 ₹40,000          Keep going👍
7      8                 ₹80,000          Keep going👍
8      9               ₹1,60,000          Keep going👍
9     10               ₹3,20,000  ✅Level 2 - Complete
10    11               ₹6,40,000          Keep going👍
11    12              ₹12,50,000          Keep going👍
12    13              ₹25,00,000          Keep going👍
13    14              ₹50,00,000          Keep going👍
14    15  ₹1,00,00,000 (1 Crore)        ✅Final Prize😎